imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_sqlite
        #host: '%database_host%'
        #port: '%database_port%'
        #dbname: '%database_name%'
        #user: '%database_user%'
        #password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# Translations
jms_translation:
    configs:
        app:
            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: [routes]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
            extractors: [alias_of_the_extractor]
            
# Assetics mapping
assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    bundles:
        - AppBundle
    assets:
        bootstrap-min-css:
            inputs: "../vendor/twbs/bootstrap/dist/css/bootstrap.min.css"
            output: 'css/bootstrap.min.css'
        bootstrap-min-css-map:
            inputs: "../vendor/twbs/bootstrap/dist/css/bootstrap.min.css.map"
            output: 'css/bootstrap.min.css.map'
        font-awesome-min-css:
            inputs: "../vendor/components/font-awesome/css/font-awesome.min.css"
            output: 'css/font-awesome.min.css'
        font-awesome-css-map:
            inputs: "../vendor/components/font-awesome/css/font-awesome.css.map"
            output: 'css/font-awesome.css.map'
        font-awesome-css-map:
            inputs: "../vendor/components/font-awesome/css/font-awesome.css.map"
            output: 'css/font-awesome.css.map'
        app-portles-css:
            inputs: "../src/AppBundle/Resources/public/css/portlets.css"
            output: 'css/portlets.css'
        fontsawesome-otf:
            inputs: "../vendor/components/font-awesome/fonts/FontAwesome.otf"
            output: 'fonts/FontAwesome.otf'
        fontsawesome-webfont-eot:
            inputs: "../vendor/components/font-awesome/fonts/fontawesome-webfont.eot"
            output: 'fonts/fontawesome-webfont.eot'
        fontsawesome-webfont-svg:
            inputs: "../vendor/components/font-awesome/fonts/fontawesome-webfont.svg"
            output: 'fonts/fontawesome-webfont.svg'
        fontsawesome-webfont-ttf:
            inputs: "../vendor/components/font-awesome/fonts/fontawesome-webfont.ttf"
            output: 'fonts/fontawesome-webfont.ttf'
        fontsawesome-webfont-woff:
            inputs: "../vendor/components/font-awesome/fonts/fontawesome-webfont.woff"
            output: 'fonts/fontawesome-webfont.woff'
        fontsawesome-webfont-woff2:
            inputs: "../vendor/components/font-awesome/fonts/fontawesome-webfont.woff2"
            output: 'fonts/fontawesome-webfont.woff2'
        jquery-js:
            inputs: "../vendor/components/jquery/jquery.min.js"
            output: 'js/jquery.min.js'
        bootstrap-min-js:
            inputs: "../vendor/twbs/bootstrap/dist/js/bootstrap.min.js"
            output: 'js/bootstrap.min.js'